# Generated by Django 5.2.12 on 2026-06-05 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interactions", "0001_initial"),
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="browsinghistory",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recommendations.book"
            ),
        ),
    ]
