# Generated by Django 5.2.12 on 2026-04-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='browsinghistory',
            options={},
        ),
        migrations.RenameField(
            model_name='browsinghistory',
            old_name='viewed_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
