# Generated by Django 5.2.12 on 2026-04-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.RemoveField(
            model_name='book',
            name='uploader',
        ),
        migrations.AlterField(
            model_name='book',
            name='favorites_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
