# Generated by Django 5.2.12 on 2026-06-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
